# This is the config file for our actions
# GitHub Actions lets you specify WHAT happens WHEN a certain event is triggered
# You can also specify on what VM / instance it runs on (default being ubuntu / linux)

# Name of the workflow
name: Git Basic Express Actions
 
# What triggers this workflow run
on: [push]
     
# What jobs are part of this workflow
jobs:
  # What is the name of this job
  Build_Express_Docker_Website:
    # What type of instance is our job running on 
    runs-on: ubuntu-latest
    # What are we doing as part of our workflow
    steps:
    # Run a command to get our files on that machine 
    # - run: git clone <git url> 
    - name: Checkout code from the repo
      uses: actions/checkout@v3 # Pre build official github action to checkout a repo 

    - name: Build the Node Express website
      run: npm install 

    - name: Test the Node Express website
      run: npm test 

    - name: Deployed (Dockerhub)
      run: docker build -t expressApp . 

    - run: ls
 
      
    